name: feedparser
version: 0.0.1
description: RSS feed parser.
authors:
- Victor Choueiri <victor.oc@gmail.com>
homepage: https://github.com/xqwzts/feedparser

environment:
  sdk: '>=1.21.0 <2.0.0'

dependencies:
  xml: "^3.0.0-alpha"
  
dev_dependencies:
  test: ^0.12.0
